server:
  port: 8091
  
#  뷰
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:     #마이바티스
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1/campusDB
    username: root
    password: "0000"
    
  devtools:       #자동재실행
    livereload:
      enabled: true
      
mybatis:
  type-aliases-package: com.campus.myapp.vo   # mybatis에서 패키지 생략 할 수 있도록 설정
  mapper-locations: mapper/*Mapper.xml 